<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bar_Control_System_2025</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Bar-Control-System-2025.Domain\Bar-Control-System-2025.Domain.csproj" />
    <ProjectReference Include="Bar-Control-System-2025.Infrastructure.Files\Bar-Control-System-2025.Infrastructure.Files.csproj" />
    <ProjectReference Include="Bar-Control-System-2025.WebApp\Bar-Control-System-2025.WebApp.csproj" />
  </ItemGroup>

</Project>
