<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bar_Control_System_2025.Infrastructure.Files</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bar-Control-System-2025.Domain\Bar-Control-System-2025.Domain.csproj" />
  </ItemGroup>

</Project>
